apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "questdb.fullname" . }}-config-scripts
  labels:
    {{- include "questdb.labels" . | nindent 4 }}
data:
    prepare_config.sh: |
      #!/bin/bash
      data_dir="$1"

      if [ -d "${data_dir}"/override_conf/ ] ; then
        # Copy override configuration files
        cp "${data_dir}"/override_conf/* "${data_dir}"/merged_conf/
      fi

      echo "Configuration preparation complete"
